export const PAYMENT_REPOSITORY = 'PAYMENT_REPOSITORY';
export const PAYMENT_ORDER_SOURCE = 'PAYMENT_ORDER_SOURCE';
export const PAYMENT_PROVIDER_GATEWAY = 'PAYMENT_PROVIDER_GATEWAY';
export const PAYMENT_WEBHOOK_VERIFIER = 'PAYMENT_WEBHOOK_VERIFIER';
